services:
  fastapi:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - HOPSWORKS_PROJECT_NAME=${HOPSWORKS_PROJECT_NAME}
      - HOPSWORKS_API_KEY=${HOPSWORKS_API_KEY}
      - HOPSWORKS_HOST=${HOPSWORKS_HOST}
    env_file:
      - .env
  streamlit:
    build: .
    command: bash -c "cd /app && PYTHONPATH=/app streamlit run src/frontend_fast_api.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://fastapi:8000
      - PYTHONPATH=/app
    depends_on:
      - fastapi
