[project]
name = "mlops-project"
version = "0.1.0"
description = "Proyecto del curso MLOps de Nood3r"
authors = [
    {name = "Jordi Quiroga",email = "jordi@jordiquiroga.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "pyarrow (>=19.0.1,<20.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "statsmodels (>=0.14.4,<0.15.0)",
    "google-cloud-bigquery (>=3.34.0,<4.0.0)",
    "db-dtypes (>=1.4.3,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
notebook = "^7.3.3"
ipykernel = "^6.29.5"

